name: ForQA
description: Flutter animation
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/get
  get: ^4.6.5

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.5

  # https://pub.dev/packages/firebase_core
  firebase_core: ^2.8.0

  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.2.19

  # https://pub.dev/packages/audioplayers
  audioplayers: ^3.0.1

  # https://pub.dev/packages/scrollable_positioned_list
  scrollable_positioned_list: ^0.3.5

  # https://pub.dev/packages/google_fonts
  google_fonts: ^4.0.3

  # https://pub.dev/packages/animated_text_kit
  animated_text_kit: ^4.2.2

  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/videos/

flutter_native_splash:
  color: "#FFEDEA"

  image: assets/images/cheesecake.png

  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cheesecake.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
